server.c File Reference
This file implements the storage server.
#include <stdio.h>
*
#include <stdlib.h>
*
#include <unistd.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <arpa/inet.h>
*
#include <netdb.h>
*
#include <string.h>
*
#include <assert.h>
*
#include <signal.h>
*
#include `utils.h`
*
#include <time.h>
*
#include <stdbool.h>
*
#include <ctype.h>
*
#include <math.h>
*
#include <sys/resource.h>
*
#include <sys/stat.h>
*
#include <pthread.h>
*
Macros
#define MAX_LISTENQUEUELEN 20
The maximum number of queued connections.
Functions
int key_exist (char key_to_search_for[MAX_KEY_LEN], int first_empty, int table_num)
Check if key exists in the server.
char * get_column_type (char column_name[MAX_COLNAME_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Get the name of the column based on name given to search for.
void split_query_get_column (char pred[MAX_VALUE_LEN], char ret[MAX_VALUE_LEN])
Get the column name from a query predicate.
void split_query_get_value (char pred[MAX_VALUE_LEN], char ret[MAX_VALUE_LEN])
Get the comparison value from a query predicate.
char * trim (char *str)
Remove whitespace from beginning and end of string.
int has_table (char table_name[MAX_TABLE_LEN])
Check if table exists in the server.
int has_column (char col_to_search[MAX_COLNAME_LEN], char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], int num_columns, int table_num)
Check if table exists in the server.
int check_column_types (char val_to_set[MAX_VALUE_LEN], int num_columns, int table_num, char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Check if the column types match the values given.
int check_mycolumns (char val_to_set[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN])
Check if the value has the correct matching column names.
int num_col_val (char val_to_set[MAX_VALUE_LEN], int num_columns)
Check if the value has the correct number of columns.
int parse_value (char val_to_set[MAX_VALUE_LEN], int table_num)
Checks if the value passes all parsing.
int check_predicates (char predicates[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10], int num_pred)
Check if all the predicates in the string are formatted correctly.
int check_mycolumns_pred (char pred_to_set[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], int num_pred)
Check if the predicate has the correct matching column names.
int num_of_predicates (char predicates[MAX_VALUE_LEN], int num_columns)
Check if the predicate string has the correct number of predicates.
int parse_predicates (char predicates[MAX_VALUE_LEN], int table_num)
Umbrella function for all predicate parsing.
void get_command (char key_to_get[MAX_KEY_LEN], char value_to_get[MAX_VALUE_LEN], int first_empty, int table_num)
Get the specified value based on the key_to_get.
void get_command_perm (char key_to_get[MAX_KEY_LEN], FILE *fileLoadData, char value_to_get[MAX_VALUE_LEN])
void get_command_specific_perm (int lineNumber, FILE *fileLoadData, char value_to_get[MAX_VALUE_LEN])
char * set_command (char key_to_set[MAX_KEY_LEN], char value_to_set[MAX_VALUE_LEN], int first_empty, int table_num)
Set the item using key_to_set and value_to_set.
char * set_command_perm (char key_to_set[MAX_KEY_LEN], char value_to_set[MAX_VALUE_LEN], FILE *fileLoadData, FILE *fileWriteData)
char * update_command (char key_to_update[MAX_KEY_LEN], char value_to_update[MAX_VALUE_LEN], int record_loc, int table_num, unsigned long int meta_data_recieved)
Set the item using key_to_set and value_to_set.
int get_column_index (char column_name[MAX_COLNAME_LEN], char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], int table_num)
Get the index of the column based on the column name given.
int predicate_true (char predicate[MAX_VALUE_LEN], int table_num, int column_index, int row_index, char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Check if the value in the row index and column index passes the predicate.
int predicate_true_perm (char predicate[MAX_VALUE_LEN], char lineFromFile[MAX_VALUE_LEN], int table_num, int column_index, int row_index, char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
int predicates_true (char predicates[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10], int row_index)
Check if the value in the row index and column index passes the predicates.
int predicates_true_perm (char predicates[MAX_VALUE_LEN], char lineFromFile[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10], int row_index)
int query_command (int sock, char predicates[MAX_VALUE_LEN], int first_empty, int table_num, int num_columns, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Query the table for matching values.
int query_command_perm (int sock, char predicates[MAX_VALUE_LEN], int table_num, int num_columns, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10], FILE *fileToLoad)
char * delete_command (char key_to_delete[MAX_KEY_LEN], int first_empty, int table_num, int num_columns, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN])
Delete the item in the server based on key_to_delete.
char * delete_command_perm (char key_to_set[MAX_KEY_LEN], FILE *fileLoadData, FILE *fileWriteData)
int handle_command (int sock, char cmd[MAX_CMD_LEN], int *auth_var)
Process a command from the client.
void * handle_client (void *arg)
int main (int argc, char *argv[])
Start the storage server.
Variables
FILE * fserverOut
struct server_record tables [MAX_TABLES][MAX_RECORDS_PER_TABLE]
int first_empty [MAX_TABLES]
struct config_params params
Detailed Description
This file implements the storage server. The storage server should be named `server` and should take a single command line argument that refers to the configuration file.
The storage server should be able to communicate with the client library functions declared in storage.h and implemented in storage.c.
Definition in file server.c.
Function Documentation
int check_column_types (char val_to_set[MAX_VALUE_LEN], int num_columns, int table_num, char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Check if the column types match the values given.
Parameters
val_to_set value to parse
num_columns number of columns for the table
table_num index of the table parsing
column_types types of the columns
Returns
returns true(1) if all column types match, false(0) if it doesn't
Definition at line 260 of file server.c.
References get_param(), and MAX_VALUE_LEN.
Referenced by parse_value().
int check_mycolumns (char val_to_set[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN])
Check if the value has the correct matching column names.
Parameters
val_to_set value to parse
num_columns number of columns for the table
table_num index of the table parsing
mycolumns names of the columns
Returns
returns true(1) if all column names match, false(-1) if it doesn't
Definition at line 360 of file server.c.
References get_param(), and MAX_VALUE_LEN.
Referenced by parse_value().
int check_mycolumns_pred (char pred_to_set[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], int num_pred)
Check if the predicate has the correct matching column names.
Parameters
pred_to_set predicate to parse
num_columns number of columns for the table
table_num index of the table parsing
mycolumns names of the columns
Returns
returns true(1) if all column names match, false(-1) if it doesn't
Definition at line 514 of file server.c.
References get_param(), has_column(), MAX_VALUE_LEN, split_query_get_column(), and trim().
Referenced by parse_predicates().
int check_predicates (char predicates[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10], int num_pred)
Check if all the predicates in the string are formatted correctly.
Parameters
predicates predicates to parse
num_columns number of columns for the table
table_num index of the table parsing
mycolumns names of the columns
column_types types of the columns
num_pred number of predicates to parse
Returns
returns true(1) if parses correctly, false(-1) if it doesn't
Definition at line 455 of file server.c.
References get_column_type(), get_param(), MAX_COLNAME_LEN, MAX_VALUE_LEN, split_query_get_column(), split_query_get_value(), and trim().
Referenced by parse_predicates().
char* delete_command (char key_to_delete[MAX_KEY_LEN], int first_empty, int table_num, int num_columns, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN])
Delete the item in the server based on key_to_delete.
Parameters
key_to_delete key to set
first_empty index of the first empty spot in keys & values
table_num index of the table parsing
num_columns number of columns in the table
mycolumns names of the columns
Returns
returns success string if it works (ERR_KEY_NOT_FOUND if key_to_delete DNE in keys)
Definition at line 1267 of file server.c.
References MAX_VALUE_LEN, and server_record::metadata.
Referenced by handle_command().
int get_column_index (char column_name[MAX_COLNAME_LEN], char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], int table_num)
Get the index of the column based on the column name given.
Parameters
column_name column name to find the type for
mycolumns names of the columns
table_num index of the table parsing
Returns
return the index of the column name given
Definition at line 906 of file server.c.
References MAX_COLUMNS_PER_TABLE.
Referenced by predicates_true().
char* get_column_type (char column_name[MAX_COLNAME_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Get the name of the column based on name given to search for.
Parameters
column_name column name to find the type for
num_columns number of columns for the table
table_num index of the table parsing
mycolumns names of the columns
column_types types of the columns
Returns
return string of type of the column
Definition at line 73 of file server.c.
Referenced by check_predicates().
void get_command (char key_to_get[MAX_KEY_LEN], char value_to_get[MAX_VALUE_LEN], int first_empty, int table_num)
Get the specified value based on the key_to_get.
Parameters
key_to_get key to serach for in keys
value_to_get value to get
first_empty index of the first empty spot in keys & values
table_num which table the get is being preformed on
Returns
returns the value of the search (ERR_KEY_NOT_FOUND if it DNE)
Definition at line 622 of file server.c.
References MAX_CMD_LEN, and MAX_VALUE_LEN.
Referenced by handle_command().
int handle_command (int sock, char cmd[MAX_CMD_LEN], int * auth_var)
Process a command from the client.
Parameters
sock The socket connected to the client.
cmd The command received from the client.
*auth_var variable that keeps track if client is authorized or not
Returns
Returns 0 on success, -1 otherwise.
Definition at line 1369 of file server.c.
References delete_command(), get_command(), get_param(), has_table(), key_exist(), MAX_CMD_LEN, MAX_ENC_PASSWORD_LEN, MAX_KEY_LEN, MAX_PATH_LEN, MAX_TABLE_LEN, MAX_USERNAME_LEN, MAX_VALUE_LEN, parse_predicates(), parse_value(), config_params::password, query_command(), sendall(), set_command(), trim(), update_command(), and config_params::username.
Referenced by main().
int has_column (char col_to_search[MAX_COLNAME_LEN], char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], int num_columns, int table_num)
Check if table exists in the server.
Parameters
col_to_search column name to search for
mycolumns names of all the columns of all the tables
num_columns number of columns for the table
table_num index of the table that is being parsed
Returns
returns column index if it exists, -1 if it doesn't
Definition at line 235 of file server.c.
Referenced by check_mycolumns_pred().
int has_table (char table_name[MAX_TABLE_LEN])
Check if table exists in the server.
Parameters
table_name table name to search for
Returns
returns table index if it exists, false(0) if it doesn't
Definition at line 210 of file server.c.
Referenced by handle_command().
int key_exist (char key_to_search_for[MAX_KEY_LEN], int first_empty, int table_num)
Check if key exists in the server.
Parameters
key_to_search key to search for in server
first_empty index of the first empty spot in keys & values
table_num the table to search the key for
Returns
returns index of record with matching key if it exists, false(-1) if it doesn't
Definition at line 47 of file server.c.
Referenced by handle_command().
int main (int argc, char * argv[])
Start the storage server.
This is the main entry point for the storage server. It reads the configuration file, starts listening on a port, and proccesses commands from clients.
Definition at line 1879 of file server.c.
References arguements::clientaddr_, arguements::clientaddrlen_, handle_command(), logger(), MAX_CMD_LEN, MAX_LISTENQUEUELEN, MAX_RECORDS_PER_TABLE, MAX_TABLES, read_config(), recvline(), config_params::server_host, config_params::server_port, and arguements::sock_.
int num_col_val (char val_to_set[MAX_VALUE_LEN], int num_columns)
Check if the value has the correct number of columns.
Parameters
val_to_set value to parse
num_columns number of columns for the table
Returns
returns true(1) if right number of columns, false(-1) if it doesn't
Definition at line 391 of file server.c.
References get_param(), and MAX_VALUE_LEN.
Referenced by parse_value().
int num_of_predicates (char predicates[MAX_VALUE_LEN], int num_columns)
Check if the predicate string has the correct number of predicates.
Parameters
predicates predicates to parse
num_columns number of columns for the table
Returns
returns number of predicates if right number of predicates, false(-1) if there are too many
Definition at line 558 of file server.c.
References get_param(), and MAX_VALUE_LEN.
Referenced by parse_predicates().
int parse_predicates (char predicates[MAX_VALUE_LEN], int table_num)
Umbrella function for all predicate parsing.
Parameters
predicates predicates to parse
table_num index of the table parsing
params config parameters from config file
Returns
returns true(1) if matches all parsing, false(0) if it doesn't
Definition at line 595 of file server.c.
References check_mycolumns_pred(), check_predicates(), and num_of_predicates().
Referenced by handle_command().
int parse_value (char val_to_set[MAX_VALUE_LEN], int table_num)
Checks if the value passes all parsing.
Parameters
val_to_set value to parse
table_num table index for the parsing
Returns
returns true(1) if matches all parsing, false(-1) if it doesn't
Definition at line 427 of file server.c.
References check_column_types(), check_mycolumns(), and num_col_val().
Referenced by handle_command().
int predicate_true (char predicate[MAX_VALUE_LEN], int table_num, int column_index, int row_index, char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Check if the value in the row index and column index passes the predicate.
Parameters
predicate predicate to test for true or false
table_num index of the table parsing
column_index index of the column to check the predicate for
row_index index of the row to check the predicate for
column_types types of the columns
Returns
returns true(1) if the predicate is true, false(0) if it doesn't
Definition at line 928 of file server.c.
References get_param(), MAX_VALUE_LEN, and split_query_get_value().
Referenced by predicates_true().
int predicates_true (char predicates[MAX_VALUE_LEN], int num_columns, int table_num, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10], int row_index)
Check if the value in the row index and column index passes the predicates.
Parameters
predicates predicates to check if true or false
numcolumns number of columns in the table
table_num index of the table parsing
mycolumns names of the columns
column_types types of the columns
row_index index of the row to check the predicate for
Returns
returns true(1) if the predicate is true, false(0) if it doesn't
Definition at line 1084 of file server.c.
References get_column_index(), get_param(), MAX_COLNAME_LEN, MAX_VALUE_LEN, predicate_true(), split_query_get_column(), and trim().
Referenced by query_command().
int query_command (int sock, char predicates[MAX_VALUE_LEN], int first_empty, int table_num, int num_columns, char mycolumns[MAX_TABLES][MAX_COLUMNS_PER_TABLE][MAX_COLNAME_LEN], char column_types[MAX_TABLES][MAX_COLUMNS_PER_TABLE][10])
Query the table for matching values.
Parameters
sock The socket connected to the client.
predicates predicates to check if true or false
first_empty index of the first empty spot in keys & values
table_num index of the table parsing
numcolumns number of columns in the table
mycolumns names of the columns
column_types types of the columns
Returns
returns the status for the server
Definition at line 1154 of file server.c.
References MAX_CMD_LEN, MAX_RECORDS_PER_TABLE, predicates_true(), recvline(), and sendall().
Referenced by handle_command().
char* set_command (char key_to_set[MAX_KEY_LEN], char value_to_set[MAX_VALUE_LEN], int first_empty, int table_num)
Set the item using key_to_set and value_to_set.
Parameters
key_to_set key to set
value_to_set value to set
first_empty index of the first empty spot in keys & values
table_num index of the table parsing
Returns
returns success string if it works (ERR_UNKNOWN if table already at max)
Definition at line 773 of file server.c.
References MAX_RECORDS_PER_TABLE, and server_record::metadata.
Referenced by handle_command().
void split_query_get_column (char pred[MAX_VALUE_LEN], char ret[MAX_VALUE_LEN])
Get the column name from a query predicate.
Parameters
pred predicate to get the column out of
ret string to return the column name too
Returns
no return value
Definition at line 103 of file server.c.
References get_param(), and MAX_VALUE_LEN.
Referenced by check_mycolumns_pred(), check_predicates(), and predicates_true().
void split_query_get_value (char pred[MAX_VALUE_LEN], char ret[MAX_VALUE_LEN])
Get the comparison value from a query predicate.
Parameters
pred predicate to get the value out of
ret string to return the column name too
Returns
no return value
Definition at line 132 of file server.c.
References get_param(), and MAX_VALUE_LEN.
Referenced by check_predicates(), and predicate_true().
char* trim (char * str)
Remove whitespace from beginning and end of string.
Parameters
str string to remove leading and trailing whitespace from
Returns
trimmed version of the string
Definition at line 160 of file server.c.
Referenced by check_mycolumns_pred(), check_predicates(), handle_command(), and predicates_true().
char* update_command (char key_to_update[MAX_KEY_LEN], char value_to_update[MAX_VALUE_LEN], int record_loc, int table_num, unsigned long int meta_data_recieved)
Set the item using key_to_set and value_to_set.
Parameters
key_to_update key to set
value_to_update value to set
record_loc index of the record to update
table_num index of the table parsing
meta_data_recieved meta data recieved from client
Returns
returns success string if it works (always successful, due to key_exist() check)
Definition at line 874 of file server.c.
References server_record::metadata.
Referenced by handle_command().