storage.c File Reference
This file contains the implementation of the storage server interface as specified in storage.h.
#include <errno.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <netdb.h>
*
#include `storage.h`
*
#include `utils.h`
*
#include <stdbool.h>
*
Functions
void * storage_connect (const char *hostname, const int port)
Connects the client to the server.
int storage_auth (const char *username, const char *passwd, void *conn)
Authenticate the client via the server.
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
Get a record from the server.
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
Insert or delete a record from the server.
int storage_query (const char *table, const char *predicates, char *keys[MAX_RECORDS_PER_TABLE], const int max_keys, void *conn)
int storage_disconnect (void *conn)
Connects the client to the server.
Variables
FILE * fclientOut
Detailed Description
This file contains the implementation of the storage server interface as specified in storage.h.
Definition in file storage.c.
Function Documentation
int storage_auth (const char * username, const char * passwd, void * conn)
Authenticate the client via the server.
Authenticate the client's connection to the server.
Parameters
username username of client
passwd password of client
conn represents connection to the server
Returns
returns 0 if successful / -1 if unsuccessfull
Definition at line 84 of file storage.c.
References ERR_AUTHENTICATION_FAILED, ERR_CONNECTION_FAIL, ERR_INVALID_PARAM, generate_encrypted_password(), logger(), MAX_CMD_LEN, recvline(), and sendall().
void* storage_connect (const char * hostname, const int port)
Connects the client to the server.
Establish a connection to the server.
Parameters
hostname hostname of the server
port port number of the server
Definition at line 27 of file storage.c.
References ERR_CONNECTION_FAIL, ERR_INVALID_PARAM, ERR_UNKNOWN, logger(), and MAX_PORT_LEN.
int storage_disconnect (void * conn)
Connects the client to the server.
Close the connection to the server.
Parameters
conn represents connection to the server
Returns
0 if successful / -1 if unsuccessful
Definition at line 531 of file storage.c.
References ERR_INVALID_PARAM.
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
Get a record from the server.
Retrieve the value associated with a key in a table.
Parameters
*table name of table being searched
*key key of the record being search
*record struct to store the value of *key
conn represents connection to the server
Returns
returns 0 if successful / -1 if unsuccessfull
Definition at line 132 of file storage.c.
References ERR_CONNECTION_FAIL, ERR_INVALID_PARAM, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, ERR_TABLE_NOT_FOUND, get_param(), logger(), MAX_CMD_LEN, storage_record::metadata, recvline(), sendall(), and storage_record::value.
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
Insert or delete a record from the server.
Store a key/value pair in a table.
Parameters
*table name of table where record is being set
*key key of the record being set
*record struct to store the value of *key
conn represents connection to the server
Returns
returns 0 if successful / -1 if unsuccessfull
Definition at line 245 of file storage.c.
References ERR_CONNECTION_FAIL, ERR_INVALID_PARAM, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, ERR_TABLE_NOT_FOUND, ERR_TRANSACTION_ABORT, logger(), MAX_CMD_LEN, storage_record::metadata, recvline(), sendall(), and storage_record::value.