utils.h File Reference
This file declares various utility functions that are can be used by the storage server and client library.
#include <stdio.h>
*
#include <pthread.h>
*
#include <sys/socket.h>
*
#include <arpa/inet.h>
*
#include `storage.h`
*
Classes
struct config_params
A struct to store config parameters.
struct server_record
Encapsulate the value associated with a key in a table.
struct arguements
Encapsulate the value associated with a key in a table.
Macros
#define LOGGING_CLIENT 1
#define LOGGING_SERVER 1
#define MAX_CMD_LEN (1024 * 8)
The max length in bytes of a command from the client to the server.
#define LOG(x) {printf x; fflush(stdout);}
A macro to log some information.
#define DBG(x) {printf x; fflush(stdout);}
A macro to output debug information.
#define DEFAULT_CRYPT_SALT `xx`
Default two character salt used for password encryption.
Functions
int sendall (const int sock, const char *buf, const size_t len)
Keep sending the contents of the buffer until complete.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int read_config (const char *config_file, struct config_params *params)
Read and load configuration parameters.
void logger (FILE *file, char *message, int LOGGING)
Generates a log message.
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
void get_param (char str[MAX_VALUE_LEN], char to_return[MAX_VALUE_LEN], int param_num, char *delims)
Split a string and return one of the split strings.
Detailed Description
This file declares various utility functions that are can be used by the storage server and client library.
Definition in file utils.h.
Macro Definition Documentation
#define DBG(x) {printf x; fflush(stdout);}
A macro to output debug information.
It is only enabled in debug builds.
Definition at line 47 of file utils.h.
#define LOG(x) {printf x; fflush(stdout);}
A macro to log some information.
Use it like this: LOG((`Hello %s`, `world\n`))
Don't forget the double parentheses, or you'll get weird errors!
Definition at line 37 of file utils.h.
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns
Returns encrypted password.
Definition at line 151 of file utils.c.
References DEFAULT_CRYPT_SALT.
Referenced by storage_auth().
void get_param (char str[MAX_VALUE_LEN], char to_return[MAX_VALUE_LEN], int param_num, char * delims)
Split a string and return one of the split strings.
Parameters
str string to be split
to_return place to return the specified paramter in str
param_num which index of the split str to return
delims string of all characters used to deliminate string
Returns
no return value
Definition at line 168 of file utils.c.
Referenced by check_column_types(), check_mycolumns(), check_mycolumns_pred(), check_predicates(), handle_command(), num_col_val(), num_of_predicates(), predicate_true(), predicates_true(), split_query_get_column(), split_query_get_value(), and storage_get().
void logger (FILE * file, char * message, int LOGGING)
Generates a log message.
Parameters
file The output stream
message Message to log.
Definition at line 131 of file utils.c.
Referenced by main(), storage_auth(), storage_connect(), storage_get(), and storage_set().
int read_config (const char * config_file, struct config_params * params)
Read and load configuration parameters.
Parameters
config_file The name of the configuration file.
params The structure where config parameters are loaded.
Returns
Return 0 on success, -1 otherwise.
Definition at line 81 of file utils.c.
References MAX_COLUMNS_PER_TABLE, config_params::password, config_params::server_host, config_params::server_port, and config_params::username.
Referenced by main().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
Returns
Return 0 on success, -1 otherwise.
In order to avoid reading more than a line from the stream, this function only reads one byte at a time. This is very inefficient, and you are free to optimize it or implement your own function.
Definition at line 52 of file utils.c.
Referenced by main(), query_command(), storage_auth(), storage_get(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
Keep sending the contents of the buffer until complete.
Returns
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
Definition at line 32 of file utils.c.
Referenced by handle_command(), query_command(), storage_auth(), storage_get(), and storage_set().